# Source: prometheus/templates/kube-state-metrics-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: prometheus
    chart: prometheus-7.3.0
    component: "kube-state-metrics"
    heritage: Tiller
    release: donating-hamster
  name: donating-hamster-prometheus-kube-state-metrics
---
