# Source: prometheus/templates/node-exporter-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: prometheus
    chart: prometheus-7.3.0
    component: "node-exporter"
    heritage: Tiller
    release: donating-hamster
  name: donating-hamster-prometheus-node-exporter
---
