# Source: prometheus/templates/server-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: prometheus
    chart: prometheus-7.3.0
    component: "server"
    heritage: Tiller
    release: donating-hamster
  name: donating-hamster-prometheus-server
---
