---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: kube-system
  labels:
    app: nginx
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.13
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: kube-system
  labels:
    name: nginx
spec:
#  type: NodePort
  ports:
    - port: 80
#      nodePort: 30080
      name: http
      targetPort: 80
#    - port: 443
#      nodePort: 30443
#      name: https
  selector:
    app: nginx
