{
 "title": "摄像头-客流分析",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "metric_name", "query": "traffic2" },
   { "name": "dis_time", "query": "1,,5,10,30,60" }
  ]
 },
 "panels": [
  {
   "title": "客流分析(/h)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time($metric_name[1h])/5)",
     "legendFormat": "人/1h"
    }
   ]
  },
  {
   "title": "男女客流(/s)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time($metric_name[1h])/5)by(gender)"
    }
   ]
  },
  {
   "title": "摄像头客流",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(traffic2[1h])/5)by(deviceid)"
    }
   ]
  },
  {
   "title": "男女比例",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 36 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time($metric_name[1h])/5) by (gender)"
    }
   ]
  },
  {
   "title": "摄像头客流",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 36 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time($metric_name[1h])/5)by(deviceid)"
    }
   ]
  },
  {
   "title": "年龄分布",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 49 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time($metric_name[1h])/5)by(age)"
    }
   ]
  }
 ]
}