{
 "title": "摄像头-grpc入口",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "project", "label": "project", "query": "label_values(project)" },
   { "name": "device_id", "label": "device_id", "query": "label_values(device_id)" },
   { "name": "age", "label": "age", "query": "label_values(age)" },
   { "name": "gender", "label": "gender", "query": "label_values(gender)" }
  ]
 },
 "panels": [
  {
   "title": "device为空(/h)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(grpc_metric{project=~\"($project)\",device_id=\"\"}[1h]))"
    }
   ]
  },
  {
   "title": "没有face数据(/h)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(grpc_metric{project=~\"($project)\",face_num=\"0\"}[1h]))"
    }
   ]
  },
  {
   "title": "时延超过4秒(/h)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(grpc_metric{project=~\"($project)\",delay!~\"0|1|2|3|-1|4\"}[1h]))"
    }
   ]
  },
  {
   "title": "客流分析(/h)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(grpc_metric{project=~\"($project)\",age=~\"($age)\",gender=~\"($gender)\",device_id=~\"($device_id)\"}[1h]))"
    }
   ]
  },
  {
   "title": "男女客流(/s)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(grpc_metric{project=~\"($project)\",age=~\"($age)\",device_id=~\"($device_id)\"}[1h]))by(gender)"
    }
   ]
  },
  {
   "title": "摄像头客流",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(grpc_metric{project=~\"($project)\",age=~\"($age)\",gender=~\"($gender)\"}[1m]))by(device_id)"
    }
   ]
  }
 ]
}