{
 "title": "显示屏-客流分析",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "metric_name", "query": "traffic1" },
   { "name": "dis_time", "query": "1,5,10,30,60" }
  ]
 },
 "panels": [
  {
   "title": "总客流",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time($metric_name[1h])/5)"
    }
   ]
  },
  {
   "title": "男女客流",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time($metric_name[1h])/5)by(gender)"
    }
   ]
  },
  {
   "title": "各显示屏客流",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time($metric_name[1h])/5)by(deviceid)"
    }
   ]
  },
  {
   "title": "男女比例",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time($metric_name[1h])/5)by(gender)"
    }
   ]
  },
  {
   "title": "年龄分布",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time($metric_name[1h])/5)by(age)"
    }
   ]
  },
  {
   "title": "屏幕客流",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time($metric_name[1h])/5)by(deviceid)"
    }
   ]
  }
 ]
}