apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: secure-foo-bar
  namespace: kong
spec:
   tls:
   - hosts:
     - secure.foo.bar
     - secure.mynginx
     secretName: tls-secret
  rules:
  - host: secure.foo.bar
    http:
      paths:
      - path: /
        backend:
          serviceName: http-svc
          servicePort: 80
  - host: secure.my.nginx
    http:
      paths:
      - path: /
        backend:
          serviceName: my-nginx
          servicePort: 8080
