apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: foo-bar
  namespace: kong
spec:
  rules:
  - host: foo.bar
    http:
      paths:
      - path: /
        backend:
          serviceName: http-svc
          servicePort: 80
  - host: my.nginx
    http:
      paths:
      - path: /
        backend:
          serviceName: my-nginx
          servicePort: 8080
