---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: kong-post
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /mnt/storage/kong-postgres

