apiVersion: v1
kind: Namespace
metadata:
  name: kube-logging
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: efk
  namespace: kube-logging
  labels:
    kubernetes.io/cluster-service: "true"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: efk
  namespace: kube-logging
subjects:
  - kind: ServiceAccount
    name: efk
    namespace: kube-logging
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
