---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: alert-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /mnt/storage/alert

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: server-pv
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /mnt/storage/server

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: alert-pvc
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: server-pvc
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
