---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: kafka-pv-0
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /mnt/storage/kafka-0
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: kafka-pv-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /mnt/storage/kafka-1
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: kafka-pv-2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /mnt/storage/kafka-2
