apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/probe: pushgateway
  labels:
    k8s-app: prometheus-pushgateway
  name: prometheus-pushgateway
  namespace: monitoring
spec:
  ports:
    - name: http
      port: 9091
      protocol: TCP
      targetPort: 9091
      nodePort: 31014
  selector:
    k8s-app: prometheus-pushgateway
    component: "prometheus-pushgateway"
  type: LoadBalancer   # NodePort
