apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  type: LoadBalancer   # NodePort
  ports:
  - name: http
    port: 3000
    targetPort: http
#    nodePort: 31012
  selector:
    app: grafana
