---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    provider: fabric8
    project: configmapcontroller
    version: 2.2.311
    group: io.fabric8.devops.apps
  name: configmapcontroller
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: configmapcontroller
  labels:
    provider: fabric8
    project: configmapcontroller
    version: 2.2.311
    group: io.fabric8.devops.apps
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: configmapcontroller
  namespace: default
