---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    provider: fabric8
    project: fabric8-console
    version: 2.2.199
    group: io.fabric8.platform.console
  name: fabric8
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: fabric8-console
  labels:
    provider: fabric8
    project: fabric8-console
    version: 2.2.199
    group: io.fabric8.plateform.console
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
