apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-metrics
  namespace: test
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: my-test-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: my-metrics
  namespace: test
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: my-metrics
  namespace: test
  labels:
    app: my-metrics
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: my-metrics
    spec:
      serviceAccount: my-metrics
      containers:
      - name: my-metrics
        image: 192.168.2.46:5000/aios/fl_metrics:0.1
        imagePullPolicy: IfNotPresent
        command: 
        - "python3"
        - "metrics.py"
        - "-u"
        - "60"
        - "-n"
        - "test"
        - "-p"
        - "/gfs/fl/metrics"
        volumeMounts:
          - mountPath: /gfs/fl
            name: metrics
      volumes:
        - name: metrics
          hostPath:
            path: /code/k8s/demo/metrics
