apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 5432
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: postgres:9.5-alpine
        name: postgres
        env:
        - name: POSTGRES_USER
          value: owner
        - name: POSTGRES_PASSWORD
          value: owner_1a2b3c
        - name: POSTGRES_DB
          value: icoastline
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-persistent-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-persistent-storage
        hostPath:
          path: "/home/data/dev/postgres"
      nodeSelector: 
        icoastline/tool: db