---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postges-pv
  labels:
    pv: postgres
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /mnt/storage/postgres

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postges-pvc
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

